# .travis.yml file for Travis CI Automated Build configuration
# Version 0.58 9/14/2015 17:32 PM

language: java

jdk:
  - oraclejdk8
  
branches:
  only:
  - master
  - develop
  - SNAP-448

sudo: required

env:
  global:
    - secure: "bV3D1DRbjRnrMCSi4bPPxHMWKL3Yf9kOYdP/ORPSEk4+dy9833swA65Am9iYyhFjBmj3uRdFV7MCjF7/jUUSprsgtTK2HMMYNDVgcgGca7xmFWmE3VXN5PEDJOOdUXgYdPhHES293VqhJJIEy2+eb6UsIOEf1un0kctv8cYFVWykxZLAtGH9UbN9slWk4zlEBl7YsoS4AE+nBTTzQE5bGHGPl4NSEyphUOV6IUWeS0+jRyoHM+ew5WoCmzxYhOoKl34PCBdTqpNT3CQIXG4mFGojsqhr9uKyk7fHxrQPWwHkWZfNO8tHBehEbq1zKKgNyTlz38GQqc2TeJ9l/x8XDGopgwzQQ5PdjysmUzOgootPJg3adLYL9qgwONFUuosvipxjQaSDsen1EEcymDLMiSfgExDALFieu8cl/PGWshiFPM+YRinnsYtZV+oRTMVkadciozjqM1Q4JnqCxieYzCnR5Za5PID6gW73WbEYAzzsLHDaZh1DcoH2kYEUlpwEKJhwL/SQPvUwZ5KqkxeJF5uPClu2db/dABLOrc5yZHcSMZ9qmZ+yrBGUvUcTK7P7JyDJUaPIpkWGgnPZE1DJduVRHyYGkwmiLmCXt/ItbhLOLadU4Nx1OZV5bP+iC1UKeUI1tS1/GuVj2A9idHHtDSZCf8wysM+qP5F4zCdQALM="
    - secure: "jG75XOROaHZJBA4jwuJSS5EWIbEumDV7TXW5PzDjrpZswEl1zrmW07xseYu22I+9ZK8wq5KU+qnRlBMJ1C3k1wYKXGcsQvip7dOsx5aU7JXjvNdQIRK3Z5ZURGpBG6hEXCwBsOzE2Z2dK80qHlquk7qgGR/ivsTnBZw3B8YXYOhaTrAgQmU3RnSt7qFTi/xBS+PvvYPyXEBsZZfRyMWBh0AeYu5+9WkuKbl0jeY/8TghZAWhFh4mzAmadsfuC0i0KQwRsOpDSUhAaSpKo2lVldmZ3AQ8adiOd7quZ7UhSmqfnWIfsXv1zHBLbR5a7iWHu3mIDmU/ZY2Wtrift+16BlgMhqIG6iFj/BEIaJUP1xV+6L0znb9V1Xfwx2feAkX1luJaT1fRb/BMJRagZQDE8sdvHK8T4bu2hi9WN7N2P2d468leF4eaGMWtE3bwqjDngBHBuNPkDfGctlhsA0ig14NnbQY3YTvKEfzdMK1GtHUGDwwlD7Ax61AUUpH2oJLuYMphecOPYxvTTkn6wbQXuBwEjuLw0oIMWjohLhpkyru3sU/qoJ2Nini7OATI3d3TACSlMqYwyw3hQRH+ZN8DprRmZ/o2dzbzfozBATP58a+LuKJa9DgjR7fMuxS8ZFjAhuERhHPnNPZUhlurppv1dAhbEq5vTUfGGfmhffnbxAc="
    - region=us-east-1 
    - STAGE_STR=DEV

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

before_deploy:
  - mkdir build_artifacts
  - cp target/enhancedsnapshots*.war build_artifacts/enhancedsnapshots_latest.war
  - mv -f target/enhancedsnapshots*.war build_artifacts/enhancedsnapshots_0.0.2_${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}.war
  - wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
  - unzip packer_0.10.1_linux_amd64.zip
  - packer build snapdirector_ami.json

deploy:
  provider: s3
  bucket: "com.sungardas.releases"
  endpoint: "s3-us-east-1.amazonaws.com"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: build_artifacts
  upload-dir: "travis-builds"
  file: "*.war"
  access_key_id:
    secure:
      f/Ep6w1BuWXbeFlj2QRgUTMt2JpNMQ7DXtZRxhTnfX4UJ8+V8sfvbxphkpV5vgCFfNIbriX3Ht4hf3pXHxyKvmODfm/YvzLGVD+THAreHq43isFNaWGIVR0/pnj3XpwolNspbjkZeSjcMH+DXmpJ23QrIwiVVlyf9YVC2hgKcxAZH0KTRzFgCO3BGLU+PKXKSjbOa9dx1XUpZMovVaFyYT33Ph3ARLvJSE7voshXx3u2QZ7rNAF98mXd3yjIbDF/5aCXDSv9tURNOMY/zxmU4KiPicQ9bVhxOOAwSIagUaueXqX2fX6mYw77+s6ouezgLonYi9VWokr4soYJrHvzcs8RY3+0Qz1QVf5GrSY+TA7RBpnhR10ErIXGZ9acV0C3+1czzkE+kLf73A/rT7C01caIcaaUzWBKfoKRfQiJI2NkQvxmQT801qbuXETXlB/ScfmZmRa2oZuAMuOCR4o608hx4Aa9o1OYtSi01HnabV76TQ19mcHeySmh2eOGJK1dGfTin/sITU+Dj6dW9N6IFV76b3nquU/INKx6y3x6cBiEj4YrB1ySWoE7NPkO85Tmm1OGvONYJDtTzotdQjZoxoVVuilrzTA6iYaf4U6dJm7j6CtLsPH07pasGsqi3VjNpmxB+lOm7H+Cuj4J39qc3tpnrVWM8uzEPkiQaXLv6Kk=
  secret_access_key:
    secure:
      FlKtQzTkLu2CCu7HXuKiAbZxCR15SO00tp2VxTeDUP4z4lsW6a8E8RQSWS8dZTUogMOHz0FgKRD56O6Hw5rywI1nmwF8FvNY9aNQFhPfSYFbxqcuscI1E9uj1UEwhAWyingocQdTgSV5123rzhlqSF5VQ+0ddPj0l2kL2lkeGDZDzcVjDDiW7M0eVOD6NF4LsDCjG1O/7GiI+uk7zzn1s2cQwOdcPM1Y/nD7gUOwz94YXLnNbortdcerZ8eby/4H7bsnDWwQ/8yHh88M/ketzrPF62KkA3NMmtwQZ5BLKPCGHw50Pk890RsG4bOTeixDFxIOcUdmp1TUmyoutDp8g58T+EVJakHROcWz1Brme2OVUldCg+tDMhhCr1IQ7r/+IOyzDsT1z64Y/JgfoJkzz0zm4O6pN5WIeqHupn3H5IFERbz2yIHby1zvzmWO9k8prKZmMRZ+0tPQS3lHc3bbTXswia8vlBMyF36nsYKgp+k6utag9NQ5DG/pQsQtNt2TjD9Ux3FJLzTTCvHPHnd4rygAW9/CMlaxEeUzSYWNGgIgGUXxR9lLFpdbaS9bcExD8ovH6rz4hQU68ilTxx8dGny9IO+Q3Wu8u3EH+/JFOx9ErqKNvCIw7fv9kO0DubW15Oaqz8uD4eOxooEdrMegfE+ZN0YpJmoqqwU2iNZ0RkQ=
  on:
    branch: master

