# .travis.yml file for Travis CI Automated Build configuration
# Version 0.58 9/14/2015 17:32 PM

language: java

jdk:
  - oraclejdk8
  
branches:
  only:
  - master
  - develop
  - SNAP-448

sudo: required

env:
  global:
    - secure: lVkwzeIUpaICOgjzs23MfQX2dERjHjTyVZRMbyCuM/lkUuWER6XBqgrgkAuAKP0ZFKNIJUSfXFqhvNOn3aNg3KJyzjOMhjZj2edH+c8P2kk9axG3/6l2lnZR+mSv0kveDu+aqX+FZsV97cP+dcw/e8oSxEfRJmK2huLRj7FrBaqrtnT+JNPQpTCenjpoOtDKXr2T2ND56SWhZxWRTnkr5sErIP2gywHxAhbnSfxI+xzCGoL1obxiO7M8KeHc9ZdFBzrvvrJmZfYUQ8m50jZ/2MstgbWZ0swKxoCl827m0gZktfcBbxDzN2eAU+odzmGGOMHkrknGbXSJLsPcN4y5Hkp0LNfZl0QL95sokqd+NEP/DHpF0cduqVoIobmKjDlcgppPy8hP7ojgecs+WgErqZAb8tveEmLUhLycM679WW93JoYTpFguEvDWk94Vd/XOEGYodF+D+He9Enn6lgTIKHNlp1eTNQt2sCG1BmBseKPTF3gwC1sXXTdKnVLvIXalpoOxZDFrC7oTw1R392Shq04Vq4hulWQ7OumsEBVF4ShIhR6LImmoisyNdfC5mvebf4ilRF2gUSdeQprX//6SQHWnxFTzQLu1BsxD0b9OglsrFnuz/6pfUi4Nree4qyL62ol6YyWMZ6KqbaG7Q68hxxrkp8D828xNHm+g21CD3Cg=
    - secure: ipZCOUqrk6Zb+rqPEoonUP6wqpNg01Y3WcaZoalwaCftNhK6CCVhWEmSkdkKFu1MD+4zBwRUw5zguR0T/TL2tSHqqblenrwI8FogZPNNfhzYPVL35+RYUev116+PliUI6hUrncKsPJ62MLlk1YXOQO9AXKpIx1t7RaOB+QeqeitLSQjV5lIm+18FpaprFX48M2gcb4HjKel42nZThHjycSDwukEvoAGbbXYygoCH9zLCuYjAVVlgjpFHmlkKxlh2QSOzhxNcAwrZqwW3Voi1cstiubZx/huXlmqBpXHh+pC2X/rA9shrD8ByXNbQhsmG8jOrNxcD0ujz/Uxno7Wjaa5FRpWuFI7gSRq56ZO+7C/Z4/ndl+8sfk5Mqvr0++7yVPWDSNOP1QQ5U3dONiBFj++LFFRJBfoarmOvR66F0S+AiZugAsOHvOTEMKJ4hFCAZBe8NwAvQZMrdBpXjw8M2ycXPm/DZ164flJoU0KuA0FnfbiUlyzWC4V1za994EGOJIhvQmumeokkAxSQwlSgiHC2CZBNV9XLixqXogrSkqmET3nmdE8svKQbyLG6Q8ft+o5TvIAnDkhb4VyqbQXv4QpiaNwip0OezTrU9iBujtpADyEGY3w2IPMrrr3qXVMx77GMx90l4DImOyOfT4A9FwMd3+nHBvG4gDtsGvYwsbg=
    - STAGE_STR=DEV

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - wget https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
  - unzip packer_0.10.1_linux_amd64.zip
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install
  - ./packer build snapdirector_ami.json

before_deploy:
  - mkdir build_artifacts
  - cp target/enhancedsnapshots*.war build_artifacts/enhancedsnapshots_latest.war
  - mv -f target/enhancedsnapshots*.war build_artifacts/enhancedsnapshots_0.0.2_${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}.war

deploy:
  provider: s3
  bucket: "com.sungardas.releases"
  endpoint: "s3-us-east-1.amazonaws.com"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: build_artifacts
  upload-dir: "travis-builds"
  file: "*.war"
  access_key_id:
    secure:
      f/Ep6w1BuWXbeFlj2QRgUTMt2JpNMQ7DXtZRxhTnfX4UJ8+V8sfvbxphkpV5vgCFfNIbriX3Ht4hf3pXHxyKvmODfm/YvzLGVD+THAreHq43isFNaWGIVR0/pnj3XpwolNspbjkZeSjcMH+DXmpJ23QrIwiVVlyf9YVC2hgKcxAZH0KTRzFgCO3BGLU+PKXKSjbOa9dx1XUpZMovVaFyYT33Ph3ARLvJSE7voshXx3u2QZ7rNAF98mXd3yjIbDF/5aCXDSv9tURNOMY/zxmU4KiPicQ9bVhxOOAwSIagUaueXqX2fX6mYw77+s6ouezgLonYi9VWokr4soYJrHvzcs8RY3+0Qz1QVf5GrSY+TA7RBpnhR10ErIXGZ9acV0C3+1czzkE+kLf73A/rT7C01caIcaaUzWBKfoKRfQiJI2NkQvxmQT801qbuXETXlB/ScfmZmRa2oZuAMuOCR4o608hx4Aa9o1OYtSi01HnabV76TQ19mcHeySmh2eOGJK1dGfTin/sITU+Dj6dW9N6IFV76b3nquU/INKx6y3x6cBiEj4YrB1ySWoE7NPkO85Tmm1OGvONYJDtTzotdQjZoxoVVuilrzTA6iYaf4U6dJm7j6CtLsPH07pasGsqi3VjNpmxB+lOm7H+Cuj4J39qc3tpnrVWM8uzEPkiQaXLv6Kk=
  secret_access_key:
    secure:
      FlKtQzTkLu2CCu7HXuKiAbZxCR15SO00tp2VxTeDUP4z4lsW6a8E8RQSWS8dZTUogMOHz0FgKRD56O6Hw5rywI1nmwF8FvNY9aNQFhPfSYFbxqcuscI1E9uj1UEwhAWyingocQdTgSV5123rzhlqSF5VQ+0ddPj0l2kL2lkeGDZDzcVjDDiW7M0eVOD6NF4LsDCjG1O/7GiI+uk7zzn1s2cQwOdcPM1Y/nD7gUOwz94YXLnNbortdcerZ8eby/4H7bsnDWwQ/8yHh88M/ketzrPF62KkA3NMmtwQZ5BLKPCGHw50Pk890RsG4bOTeixDFxIOcUdmp1TUmyoutDp8g58T+EVJakHROcWz1Brme2OVUldCg+tDMhhCr1IQ7r/+IOyzDsT1z64Y/JgfoJkzz0zm4O6pN5WIeqHupn3H5IFERbz2yIHby1zvzmWO9k8prKZmMRZ+0tPQS3lHc3bbTXswia8vlBMyF36nsYKgp+k6utag9NQ5DG/pQsQtNt2TjD9Ux3FJLzTTCvHPHnd4rygAW9/CMlaxEeUzSYWNGgIgGUXxR9lLFpdbaS9bcExD8ovH6rz4hQU68ilTxx8dGny9IO+Q3Wu8u3EH+/JFOx9ErqKNvCIw7fv9kO0DubW15Oaqz8uD4eOxooEdrMegfE+ZN0YpJmoqqwU2iNZ0RkQ=
  on:
    branch: master

