---
- name: install packages
  yum: name="{{item}}" state=installed
  with_items:
    - python-setuptools
    - fuse
    - jsvc
    - libxml2

- name: install sdfs

  shell: rpm -ivh --force https://s3.amazonaws.com/607481993316.sungardas-enhancedsnapshot.us-east-1/sdfs-3.2.7-1.x86_64.sungard.rpm


- lineinfile: dest=/etc/security/limits.conf state=present
            line='* hardnofile 65535'
- lineinfile: dest=/etc/security/limits.conf state=present
            line='* soft nofile 65535'
